apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
      log_level: info

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
    # Kubernetes pods discovery
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
      - role: pod
      pipeline_stages:
      - cri: {}
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_pod_label_app
        target_label: app
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      # Filter for Tracee pods specifically
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: tracee
        action: keep

    # Dedicated Tracee log file collection
    - job_name: tracee-logs
      static_configs:
      - targets:
        - localhost
        labels:
          job: tracee-security
          __path__: /tmp/tracee-logs/tracee.log
      pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            event: eventName
            msg: message
      - labels:
          level:
          event:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

