apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      tolerations:
      - operator: Exists
      containers:
      - name: promtail
        securityContext:
          runAsUser: 0
          privileged: true
        image: grafana/promtail:2.9.8
        args:
        - -config.file=/etc/promtail/promtail.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/promtail
        - name: logs
          mountPath: /var/log/pods
          readOnly: true
        - name: containers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: tracee-logs
          mountPath: /tmp/tracee-logs
          readOnly: true
        - name: run
          mountPath: /run/promtail
      volumes:
      - name: config
        configMap:
          name: promtail-config
      - name: logs
        hostPath:
          path: /var/log/pods
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
      - name: tracee-logs
        hostPath:
          path: /tmp/tracee-logs
      - name: run
        hostPath:
          path: /run/promtail

